### ISSUE TITLE
Code for the info (demo) version

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#12]
According to @HedgehogHolly's recommendations https://github.com/neontribe/contemplating-advice/issues/1

We should be able to get away with sectioning off the selectors we care about and documenting with example alternatives. Plus maybe an illustrative readme with some visual and instructions about how to change the various things. Not too detailed at this stage, devs will do the work - it might be handy though as a guide to our trial charities so they see what they can and can't change.

If we go ahead with the CMS part of the project - the docs will need to be different.

## Plan
- [x]  Maybe alter css to make it easier to customise - do as we go.
- [x] Think about forking vs/ shared repo - gh-pages etc (start withe release branches)
see #36 for domain details.
- [ ]  Add styles from #26 
- [ ] Add copy from #13 @HedgehogHolly working on this
- [ ] Add illustrations from #27

**Comment by katjam** [comment]
Illustrated list of elements to allow custom:
https://realtimeboard.com/app/board/o9J_kyLGU0c=/

Haven design review:
https://realtimeboard.com/app/board/o9J_kyqrKAU=/

**Comment by katquatermass** [comment]
#13 is not closed because it has two outstanding bits of content BUT it is ready for dev because those pieces are separate (privacy and supporters) to the flow that I'd like to get people to test internally and with friends

**Comment by katjam** [comment]
Closing in favour of small dev sub tasks.
