### ISSUE TITLE
Add i18n as a way for content to differ between charities

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#149]
## User Story
Our charites have their own copy. Maybe i18n will help the copy swap be safe and easy?

## Plan
- [x] Add similar to functionality with Keyed copy
- [x] Icons in Keyed list

## Shard cards:
- [x] Contemplating action backgrounds have shifted. Will be improved with css refector. #166
- [ ] Stories to have dynamic count
- [ ] Info to have dynamic count
- [ ] #172 Contact and Call to action can be phone, iframe (chat/survey), email?
- [ ] #169 Supporters page (re-card and decide what we want/need this page to be)
- [ ] #163 Privacy page - add links back in to Stored & Rights sections. Decide what we need for templating customers

## Acceptance
- [ ] App copy is sourced from a locale file
- [ ] App content matches release (contemplatingaction.org.uk)

**Comment by katjam** [comment]
@roseb04 Are the supporters pages going to all be identical to Contemplating Action, or different per charity? Do we need them to be able to thank own partners or just stick a CAST logo in the footer? Are the others relevant to these sites?
