### ISSUE TITLE
VVV/EE Generate GA tracking on first page load

### ISSUE THREAD

**Issue by Nikomus** [neontribe/contemplating-action#197]
## Description
Google analytics are only initialised on update events. This means that the first page load for a new visitor won't be recorded, with tracking starting from after they've navigated to a new page.

## Plan
- [x] Investigate if this is a problem we'd like to fix or not.
- [x] Fix it

## Acceptance Criteria
- [ ] For all brands a GA tracking event is sent on initial page load of home page when the site is visited.
- [ ] Note that it is likely at least one brand has not been updated (see list below)
- [ ] www.youmattertoday.org.uk (Haven)
- [ ] www.contemplatingaction.org.uk
- [ ] neontribe.github.io/ca-hospice-hope & https://www.hopestories.org.uk/
- [ ] neontribe.github.io/ca-seap
- [ ] neontribe.github.io/ca-samaritans
