### ISSUE TITLE
Catch-up meeting 26 Feb

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#38]
## Description
Agenda - go through issues list (focus on prep milestone)

## Actions
- [x] Create an issue to follow on from #25 getting blog ready @katquatermass 
- [x] Copy update #13 @katquatermass 
- [ ] Haven permission to use a story @katquatermass 
- [x] begin survey & metrics discussions @katjam @katquatermass @roseb04 (but mostly Kat until next week) Conversation in #7 and #28

**Comment by katjam** [comment]
@katquatermass I guess close this once we/you've done actions?

**Comment by katjam** [comment]
@katquatermass You are probably still doing ask Haven permission - but can we close this?

**Comment by katjam** [comment]
Closing will be AC on #47
